import { Box, Center, Heading, useBoolean } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import bg from 'public/bg.png'
import { Card } from '../components/card'

const Home: NextPage = () => {
  const [isFlipped, flipped] = useBoolean(false)

  return (
    <Box bg="green.100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center h="100vh" sx={{ perspective: '1600px' }}>
        <Card bg={bg} onClick={flipped.toggle} rotation={isFlipped ? 180 : 360}>
          <Heading color="red.700">Delante</Heading>
        </Card>
        <Card bg={bg} onClick={flipped.toggle} rotation={isFlipped ? 0 : 180}>
          <Heading color="red.700">Detras</Heading>
        </Card>
      </Center>
    </Box>
  )
}

export default Home
